# Generated by Django 3.2 on 2022-05-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
                ('cont_numbers', models.IntegerField()),
                ('list_numbers', models.JSONField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default='page-slug', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
