# Generated by Django 3.2 on 2022-05-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='age',
            field=models.IntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cont_numbers',
            field=models.IntegerField(verbose_name='Quantidade de Numeros'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
