# Generated by Django 4.0.4 on 2022-06-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ticket_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
